import { FLAG_ENTITY_TYPE_DISPLAY } from '@/constants/entity-type-display';
import { FLAG_STATUS_DISPLAY, FLAG_TYPE_DISPLAY } from '@/constants/risk-flag-display';
import { WILMS_REPORT_TYPE, type WilmsExportDocument } from '@/features/export/types';
import { generateReportId } from '@/features/export/utils/report-id';
import { getWilmsEnvironment } from '@/features/export/utils/environment';
import {
  formatExportDate,
  formatExportTimestamp,
  formatPesewasForExport,
} from '@/features/export/utils/formatters';
import type {
  FlagTimelineEvent,
  RiskFlagListResponse,
  RiskFlagSummary,
} from '@/types/risk-flag';

export interface RiskFlagsExportInput {
  data: RiskFlagListResponse;
  flags: RiskFlagSummary[];
  generatedBy: string;
  selectedFlag?: RiskFlagSummary | null;
  timeline?: FlagTimelineEvent[];
}

export function buildRiskFlagsExportDocument(input: RiskFlagsExportInput): WilmsExportDocument {
  const reportId = generateReportId(WILMS_REPORT_TYPE.RISK_FLAGS);
  const generatedAt = formatExportTimestamp();
  const { data, flags, selectedFlag, timeline } = input;

  const sections: WilmsExportDocument['sections'] = [
    {
      title: 'Flag Summary',
      type: 'metrics',
      metrics: [
        { label: 'Open Flags', value: String(data.summary.openFlags), tone: 'danger' },
        { label: 'Blacklisted', value: String(data.summary.blacklisted), tone: 'danger' },
        {
          label: 'Outstanding Arrears',
          value: formatPesewasForExport(data.summary.outstandingArrearsPesewas),
        },
        { label: 'High-Risk Borrowers', value: String(data.summary.highRiskBorrowers) },
      ],
    },
    {
      title: 'Flag Type Breakdown',
      type: 'table',
      table: {
        headers: ['Flag Type', 'Count'],
        rows: data.typeBreakdown.map((entry) => [entry.label, String(entry.count)]),
      },
    },
    {
      title: 'Risk Flags',
      type: 'table',
      table: {
        headers: [
          'Flag ID',
          'Entity',
          'Entity ID',
          'Type',
          'Flag Type',
          'Community',
          'Officer',
          'Raised',
          'Arrears (GHS)',
          'Status',
        ],
        rows: flags.map((flag) => [
          flag.id,
          flag.entityName,
          flag.entityId,
          FLAG_ENTITY_TYPE_DISPLAY[flag.entityType],
          FLAG_TYPE_DISPLAY[flag.flagType].label,
          flag.community,
          flag.officerName,
          formatExportDate(flag.raisedAt),
          formatPesewasForExport(flag.arrearsPesewas).replace('GHS ', ''),
          FLAG_STATUS_DISPLAY[flag.status].label,
        ]),
      },
    },
  ];

  if (selectedFlag) {
    sections.push({
      title: 'Selected Flag Details',
      type: 'summary',
      summaryItems: [
        { label: 'Flag ID', value: selectedFlag.id },
        { label: 'Entity Name', value: selectedFlag.entityName },
        { label: 'Entity ID', value: selectedFlag.entityId },
        { label: 'Group', value: selectedFlag.groupName ?? '—' },
        { label: 'Community', value: selectedFlag.community },
        { label: 'Officer', value: selectedFlag.officerName },
        {
          label: 'Weeks Overdue',
          value: selectedFlag.weeksOverdue ? String(selectedFlag.weeksOverdue) : '—',
        },
        { label: 'Arrears', value: formatPesewasForExport(selectedFlag.arrearsPesewas) },
        {
          label: 'Members',
          value:
            selectedFlag.activeMembers != null && selectedFlag.totalMembers != null
              ? `${selectedFlag.activeMembers}/${selectedFlag.totalMembers}`
              : '—',
        },
        { label: 'Raised Date', value: formatExportDate(selectedFlag.raisedAt) },
        { label: 'Flag Type', value: FLAG_TYPE_DISPLAY[selectedFlag.flagType].label },
        { label: 'Status', value: FLAG_STATUS_DISPLAY[selectedFlag.status].label },
      ],
    });

    if (timeline?.length) {
      sections.push({
        title: 'Flag Timeline',
        type: 'table',
        table: {
          headers: ['Event', 'Recorded At'],
          rows: timeline.map((event) => [event.message, formatExportDate(event.recordedAt.slice(0, 10))]),
        },
      });
    }
  }

  sections.push({
    title: 'Audit Information',
    type: 'summary',
    summaryItems: [
      { label: 'Report ID', value: reportId },
      { label: 'Generated By', value: input.generatedBy },
      { label: 'Generated At', value: generatedAt },
      { label: 'Environment', value: getWilmsEnvironment() },
      { label: 'Flags Exported', value: String(flags.length) },
    ],
  });

  return {
    metadata: {
      reportType: WILMS_REPORT_TYPE.RISK_FLAGS,
      reportTitle: 'Risk & Flags Report',
      reportId,
      generatedAt,
      generatedBy: input.generatedBy,
      environment: getWilmsEnvironment(),
      referencePrefix: 'RSK',
    },
    executiveSummary: `Risk & Flags export covering ${flags.length} records with ${data.summary.openFlags} open flags and ${formatPesewasForExport(data.summary.outstandingArrearsPesewas)} outstanding arrears.`,
    sections,
    orientation: flags.length > 8 ? 'landscape' : 'portrait',
  };
}
