import type { SettingsUserRecord, SystemSettings } from '@/types/settings';
import { WILMS_REPORT_TYPE, type WilmsExportDocument } from '@/features/export/types';
import { generateReportId } from '@/features/export/utils/report-id';
import { getWilmsEnvironment } from '@/features/export/utils/environment';
import { formatExportTimestamp, formatPesewasForExport } from '@/features/export/utils/formatters';

export interface SettingsExportInput {
  settings: SystemSettings;
  users: SettingsUserRecord[];
  generatedBy: string;
  activeSectionLabel: string;
}

export function buildSettingsExportDocument(input: SettingsExportInput): WilmsExportDocument {
  const reportId = generateReportId(WILMS_REPORT_TYPE.SETTINGS);
  const generatedAt = formatExportTimestamp();

  return {
    metadata: {
      reportType: WILMS_REPORT_TYPE.SETTINGS,
      reportTitle: `System Settings — ${input.activeSectionLabel}`,
      reportId,
      generatedAt,
      generatedBy: input.generatedBy,
      environment: getWilmsEnvironment(),
      referencePrefix: 'SET',
    },
    executiveSummary: `WILMS configuration snapshot for ${input.activeSectionLabel} as of ${generatedAt}.`,
    sections: [
      {
        title: 'Organisation',
        type: 'summary',
        summaryItems: [
          { label: 'System Name', value: 'WILMS' },
          { label: 'Organisation', value: "Women's Interest-Free Loan Management System" },
          { label: 'Primary Colour', value: '#0F6E56' },
          { label: 'Accent Colour', value: '#BA7517' },
        ],
      },
      {
        title: 'Security & Access',
        type: 'summary',
        summaryItems: [
          { label: 'Two-Factor Authentication', value: 'Required for Super Admin' },
          { label: 'Session Timeout', value: '30 minutes' },
          { label: 'Password Policy', value: 'Strong — 12+ chars' },
          { label: 'IP Allowlist', value: 'Disabled (demo)' },
          { label: 'Failed Login Lockout', value: '5 attempts' },
        ],
      },
      {
        title: 'Loan Rules',
        type: 'summary',
        summaryItems: [
          { label: 'Max Loan Amount', value: 'GHS 5,000' },
          { label: 'Min Group Size', value: '5 members' },
          { label: 'Default Loan Duration', value: '12 weeks' },
          { label: 'Allow Rollovers', value: 'Yes' },
          { label: 'Grace Period', value: '3 days' },
          { label: 'Admin Fee', value: formatPesewasForExport(input.settings.adminFeePesewas) },
        ],
      },
      {
        title: 'SMS & Communications',
        type: 'summary',
        summaryItems: [
          { label: 'SMS Provider', value: 'SMSNotifyGH' },
          { label: 'Payment Confirmation SMS', value: input.settings.smsNotificationsEnabled ? 'Enabled' : 'Disabled' },
          { label: 'Missed Payment Alerts', value: 'Enabled' },
          { label: 'Approval Notifications', value: 'Enabled' },
          { label: 'SMS Sender ID', value: 'WILMS-GH' },
        ],
      },
      {
        title: 'User Management',
        type: 'table',
        table: {
          headers: ['User', 'Role', 'Last Login', 'Status'],
          rows: input.users.map((entry) => [
            entry.displayName,
            entry.roleLabel,
            entry.lastLoginLabel,
            entry.status,
          ]),
        },
      },
      {
        title: 'Audit Information',
        type: 'summary',
        summaryItems: [
          { label: 'Report ID', value: reportId },
          { label: 'Generated By', value: input.generatedBy },
          { label: 'Generated At', value: generatedAt },
          { label: 'Active Section', value: input.activeSectionLabel },
          { label: 'Last Settings Sync', value: input.settings.updatedAt.slice(0, 10) },
        ],
      },
    ],
    orientation: 'portrait',
  };
}
