import { WILMS_REPORT_TYPE_PREFIX } from '@/features/export/constants/branding';
import type { TabularExportInput, WilmsExportDocument } from '@/features/export/types';
import { generateReportId } from '@/features/export/utils/report-id';
import { getWilmsEnvironment } from '@/features/export/utils/environment';
import { formatExportTimestamp } from '@/features/export/utils/formatters';

export function buildTabularExportDocument(input: TabularExportInput): WilmsExportDocument {
  const generatedAt = formatExportTimestamp();
  const reportId = input.reportId ?? generateReportId(input.reportType);
  const referencePrefix = WILMS_REPORT_TYPE_PREFIX[input.reportType] ?? 'RPT';

  return {
    metadata: {
      reportType: input.reportType,
      reportTitle: input.reportTitle,
      reportId,
      generatedAt,
      generatedBy: input.generatedBy,
      environment: getWilmsEnvironment(),
      referencePrefix,
      entityRef: input.entityRef,
    },
    executiveSummary:
      input.executiveSummary ??
      `${input.reportTitle} containing ${input.rows.length} record(s), generated for official WILMS reporting.`,
    sections: [
      ...(input.metrics?.length
        ? [
            {
              title: 'Key Metrics',
              type: 'metrics' as const,
              metrics: input.metrics,
            },
          ]
        : []),
      {
        title: 'Detailed Records',
        type: 'table',
        table: {
          headers: input.headers,
          rows: input.rows,
          caption: input.reportTitle,
        },
      },
      {
        title: 'Audit Information',
        type: 'summary',
        summaryItems: [
          { label: 'Report ID', value: reportId },
          { label: 'Generated By', value: input.generatedBy },
          { label: 'Generated At', value: generatedAt },
          { label: 'Environment', value: getWilmsEnvironment() },
          { label: 'Total Records', value: String(input.rows.length) },
        ],
      },
    ],
    orientation: input.headers.length > 6 ? 'landscape' : 'portrait',
  };
}
