import { PERMISSION, type PermissionId } from './permissions';
import { USER_ROLE, type UserRole } from './roles';

const ROLE_PERMISSIONS: Record<UserRole, PermissionId[]> = {
  [USER_ROLE.SUPER_ADMIN]: Object.values(PERMISSION),
  [USER_ROLE.COLLECTOR]: [
    PERMISSION.ACCESS_COLLECTOR_PORTAL,
    PERMISSION.REGISTER_BORROWERS,
    PERMISSION.MANAGE_GROUPS,
    PERMISSION.VIEW_ASSIGNED_BORROWERS,
    PERMISSION.RECORD_COLLECTIONS,
    PERMISSION.RECORD_EXPENSES,
  ],
  [USER_ROLE.REGISTRATION_OFFICER]: [
    PERMISSION.ACCESS_REGISTRATION_PORTAL,
    PERMISSION.REGISTER_BORROWERS,
    PERMISSION.EDIT_BORROWERS,
    PERMISSION.EDIT_PENDING_REGISTRATIONS,
    PERMISSION.CAPTURE_DOCUMENTS,
    PERMISSION.UPLOAD_SIGNATURES,
    PERMISSION.GPS_VERIFICATION,
  ],
  [USER_ROLE.APPROVER]: [
    PERMISSION.ACCESS_APPROVER_PORTAL,
    PERMISSION.REVIEW_APPLICATIONS,
    PERMISSION.APPROVE_LOANS,
    PERMISSION.REJECT_LOANS,
    PERMISSION.APPROVE_BORROWERS,
    PERMISSION.REVIEW_RISK_FLAGS,
  ],
  [USER_ROLE.AUDITOR]: [
    PERMISSION.ACCESS_AUDITOR_PORTAL,
    PERMISSION.VIEW_AUDIT_LOG,
    PERMISSION.VIEW_REPORTS,
    PERMISSION.EXPORT_REPORTS,
    PERMISSION.REVIEW_RISK_FLAGS,
  ],
};

export function getPermissionsForRole(role: UserRole): Set<PermissionId> {
  return new Set(ROLE_PERMISSIONS[role]);
}

export function roleHasPermission(role: UserRole, permission: PermissionId): boolean {
  return getPermissionsForRole(role).has(permission);
}
