import {
  WILMS_CONFIDENTIALITY_NOTICE,
  WILMS_EXPORT_COLORS,
  WILMS_ORG_FULL_NAME,
  WILMS_ORG_IDENTIFIER,
  WILMS_ORG_NAME,
} from '@/features/export/constants/branding';
import type { WilmsExportDocument } from '@/features/export/types';

export function escapeCsvCell(value: string | null | undefined): string {
  const normalized = value ?? '';

  if (normalized.includes('"') || normalized.includes(',') || normalized.includes('\n')) {
    return `"${normalized.replace(/"/g, '""')}"`;
  }

  return normalized;
}

function buildMetadataLines(document: WilmsExportDocument): string[] {
  const { metadata } = document;

  return [
    `# ${WILMS_ORG_NAME} Report`,
    `# ${WILMS_ORG_FULL_NAME}`,
    `# Organization: ${WILMS_ORG_IDENTIFIER}`,
    `# Report Title: ${metadata.reportTitle}`,
    `# Report ID: ${metadata.reportId}`,
    `# Generated: ${metadata.generatedAt}`,
    `# Generated By: ${metadata.generatedBy}`,
    `# Environment: ${metadata.environment}`,
    `# ${WILMS_CONFIDENTIALITY_NOTICE}`,
    '#',
  ];
}

function buildTableCsv(headers: string[], rows: string[][], totalsRow?: string[]): string {
  const lines = [headers.map(escapeCsvCell).join(',')];

  for (const row of rows) {
    lines.push(row.map((cell) => escapeCsvCell(cell)).join(','));
  }

  if (totalsRow) {
    lines.push(totalsRow.map((cell) => escapeCsvCell(cell)).join(','));
  }

  return lines.join('\n');
}

export function buildWilmsCsvContent(document: WilmsExportDocument): string {
  const blocks: string[] = [...buildMetadataLines(document)];

  if (document.executiveSummary) {
    blocks.push(`Executive Summary,${escapeCsvCell(document.executiveSummary)}`, '');
  }

  for (const section of document.sections) {
    blocks.push(`Section,${escapeCsvCell(section.title)}`);

    if (section.type === 'summary' && section.summaryItems) {
      blocks.push(
        buildTableCsv(
          ['Field', 'Value'],
          section.summaryItems.map((item) => [item.label, item.value]),
        ),
      );
    }

    if (section.type === 'metrics' && section.metrics) {
      blocks.push(
        buildTableCsv(
          ['Metric', 'Value'],
          section.metrics.map((metric) => [metric.label, metric.value]),
        ),
      );
    }

    if (section.type === 'table' && section.table) {
      blocks.push(
        buildTableCsv(section.table.headers, section.table.rows, section.table.totalsRow),
      );
    }

    if (section.type === 'text' && section.content) {
      blocks.push(`Notes,${escapeCsvCell(section.content)}`);
    }

    blocks.push('');
  }

  if (document.signatures?.length) {
    blocks.push(
      buildTableCsv(
        ['Signature Role', 'Name'],
        document.signatures.map((signature) => [signature.label, signature.name ?? '']),
      ),
    );
  }

  blocks.push(`Footer,${escapeCsvCell(WILMS_CONFIDENTIALITY_NOTICE)}`);
  blocks.push(`Report ID,${document.metadata.reportId}`);
  blocks.push(`Brand Color Primary,${WILMS_EXPORT_COLORS.primary}`);

  return blocks.join('\n');
}

export function downloadWilmsCsv(
  document: WilmsExportDocument,
  filename: string,
): void {
  const content = buildWilmsCsvContent(document);
  const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = window.document.createElement('a');

  link.href = url;
  link.download = filename.endsWith('.csv') ? filename : `${filename}.csv`;
  link.style.display = 'none';
  window.document.body.appendChild(link);
  link.click();
  window.document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/** @deprecated Use buildWilmsCsvContent from the export framework. */
export function buildCsvContent(headers: string[], rows: string[][]): string {
  return buildTableCsv(headers, rows);
}

/** @deprecated Use downloadWilmsCsv from the export framework. */
export function downloadCsvFile(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = window.document.createElement('a');

  link.href = url;
  link.download = filename;
  link.style.display = 'none';
  window.document.body.appendChild(link);
  link.click();
  window.document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
