import ExcelJS from 'exceljs';
import {
  WILMS_CONFIDENTIALITY_NOTICE,
  WILMS_EXPORT_COLORS,
  WILMS_ORG_FULL_NAME,
  WILMS_ORG_IDENTIFIER,
  WILMS_ORG_NAME,
  WILMS_WORKBOOK_TITLE,
} from '@/features/export/constants/branding';
import type { WilmsExportDocument, WilmsExportSection } from '@/features/export/types';

function applyHeaderRowStyle(row: ExcelJS.Row): void {
  row.font = { bold: true, color: { argb: 'FFFFFFFF' }, name: 'Calibri', size: 11 };
  row.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF0F6E56' },
  };
  row.alignment = { vertical: 'middle', horizontal: 'left' };
  row.height = 22;
}

function applySectionTitleStyle(cell: ExcelJS.Cell): void {
  cell.font = { bold: true, size: 13, color: { argb: 'FF0F6E56' }, name: 'Calibri' };
}

function addSummarySection(
  sheet: ExcelJS.Worksheet,
  section: WilmsExportSection,
  startRow: number,
): number {
  let rowIndex = startRow;
  sheet.getCell(`A${rowIndex}`).value = section.title;
  applySectionTitleStyle(sheet.getCell(`A${rowIndex}`));
  rowIndex += 1;

  const headerRow = sheet.getRow(rowIndex);
  headerRow.values = ['Field', 'Value'];
  applyHeaderRowStyle(headerRow);
  rowIndex += 1;

  for (const item of section.summaryItems ?? []) {
    const row = sheet.getRow(rowIndex);
    row.values = [item.label, item.value];
    rowIndex += 1;
  }

  return rowIndex + 1;
}

function addTableSection(
  sheet: ExcelJS.Worksheet,
  section: WilmsExportSection,
  startRow: number,
): number {
  let rowIndex = startRow;
  sheet.getCell(`A${rowIndex}`).value = section.title;
  applySectionTitleStyle(sheet.getCell(`A${rowIndex}`));
  rowIndex += 1;

  const table = section.table!;

  const headerRow = sheet.getRow(rowIndex);
  headerRow.values = table.headers;
  applyHeaderRowStyle(headerRow);
  rowIndex += 1;

  table.rows.forEach((values, index) => {
    const row = sheet.getRow(rowIndex);
    row.values = values;

    if (index % 2 === 1) {
      row.eachCell((cell) => {
        cell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFF5F7F6' },
        };
      });
    }

    rowIndex += 1;
  });

  if (table.totalsRow) {
    const totals = sheet.getRow(rowIndex);
    totals.values = table.totalsRow;
    totals.font = { bold: true };
    rowIndex += 1;
  }

  sheet.views = [{ state: 'frozen', ySplit: startRow + 1 }];
  sheet.autoFilter = {
    from: { row: startRow + 1, column: 1 },
    to: { row: rowIndex - 1, column: table.headers.length },
  };

  return rowIndex + 1;
}

function populateMetadataSheet(sheet: ExcelJS.Worksheet, document: WilmsExportDocument): void {
  const rows: Array<[string, string]> = [
    [WILMS_ORG_NAME, WILMS_ORG_FULL_NAME],
    ['Organization Identifier', WILMS_ORG_IDENTIFIER],
    ['Workbook Title', WILMS_WORKBOOK_TITLE],
    ['Report Title', document.metadata.reportTitle],
    ['Report ID', document.metadata.reportId],
    ['Generated Date', document.metadata.generatedAt],
    ['Generated By', document.metadata.generatedBy],
    ['Environment', document.metadata.environment],
    ['Report Type', document.metadata.reportType],
  ];

  if (document.metadata.entityRef) {
    rows.push(['Entity Reference', document.metadata.entityRef]);
  }

  if (document.executiveSummary) {
    rows.push(['Executive Summary', document.executiveSummary]);
  }

  rows.forEach(([label, value], index) => {
    const rowNumber = index + 1;
    sheet.getCell(`A${rowNumber}`).value = label;
    sheet.getCell(`A${rowNumber}`).font = { bold: true, color: { argb: 'FF0F6E56' } };
    sheet.getCell(`B${rowNumber}`).value = value;
    sheet.getCell(`B${rowNumber}`).alignment = { wrapText: true };
  });

  sheet.getColumn(1).width = 28;
  sheet.getColumn(2).width = 72;
  sheet.getCell('A20').value = WILMS_CONFIDENTIALITY_NOTICE;
  sheet.getCell('A20').font = { italic: true, color: { argb: 'FF993C1D' } };
}

function populateAuditSheet(sheet: ExcelJS.Worksheet, document: WilmsExportDocument): void {
  populateMetadataSheet(sheet, document);
  sheet.name = 'Audit Information';
}

export async function downloadWilmsExcel(
  document: WilmsExportDocument,
  filename: string,
): Promise<void> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = document.metadata.generatedBy;
  workbook.created = new Date();
  workbook.modified = new Date();
  workbook.title = WILMS_WORKBOOK_TITLE;
  workbook.subject = document.metadata.reportTitle;
  workbook.keywords = `${document.metadata.reportId};${document.metadata.reportType}`;

  const summarySheet = workbook.addWorksheet('Executive Summary');
  populateMetadataSheet(summarySheet, document);

  const metricsSection = document.sections.find((section) => section.type === 'metrics');
  if (metricsSection?.metrics?.length) {
    const statsSheet = workbook.addWorksheet('Statistics');
    const header = statsSheet.getRow(1);
    header.values = ['Metric', 'Value'];
    applyHeaderRowStyle(header);
    metricsSection.metrics.forEach((metric, index) => {
      statsSheet.getRow(index + 2).values = [metric.label, metric.value];
    });
    statsSheet.getColumn(1).width = 32;
    statsSheet.getColumn(2).width = 24;
  }

  const detailSections = document.sections.filter(
    (section) => section.type === 'table' || section.type === 'summary',
  );

  detailSections.forEach((section, index) => {
    const sheet = workbook.addWorksheet(
      section.type === 'table'
        ? section.title.slice(0, 31)
        : `${section.title.slice(0, 24)} ${index + 1}`.slice(0, 31),
    );
    if (section.type === 'summary') {
      addSummarySection(sheet, section, 1);
    } else if (section.type === 'table') {
      addTableSection(sheet, section, 1);
    }

    sheet.columns.forEach((column) => {
      column.width = 18;
    });
  });

  populateAuditSheet(workbook.addWorksheet('Audit Information'), document);

  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });
  const url = URL.createObjectURL(blob);
  const link = window.document.createElement('a');

  link.href = url;
  link.download = filename.endsWith('.xlsx') ? filename : `${filename}.xlsx`;
  link.style.display = 'none';
  window.document.body.appendChild(link);
  link.click();
  window.document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export { WILMS_EXPORT_COLORS };
