import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  WILMS_CONFIDENTIALITY_NOTICE,
  WILMS_EXPORT_COLORS,
  WILMS_ORG_FULL_NAME,
  WILMS_ORG_IDENTIFIER,
  WILMS_ORG_NAME,
} from '@/features/export/constants/branding';
import { buildRegistrationAgreementPrintHtml } from '@/features/export/builders/registration-agreement-print-html';
import type { WilmsExportDocument, WilmsExportSection } from '@/features/export/types';
import type { RegistrationAgreementContent } from '@/utils/registration-agreement-fields';

const PRIMARY_RGB: [number, number, number] = [15, 110, 86];
const ACCENT_RGB: [number, number, number] = [186, 117, 23];
const MUTED_RGB: [number, number, number] = [92, 92, 92];

function drawDocumentHeader(doc: jsPDF, document: WilmsExportDocument): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setFillColor(...PRIMARY_RGB);
  doc.rect(0, 0, pageWidth, 28, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(WILMS_ORG_NAME, 14, 12);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text(WILMS_ORG_FULL_NAME, 14, 18);
  doc.text(WILMS_ORG_IDENTIFIER, 14, 23);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text(document.metadata.reportTitle, pageWidth - 14, 12, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text(`Report ID: ${document.metadata.reportId}`, pageWidth - 14, 18, { align: 'right' });
  doc.text(document.metadata.generatedAt, pageWidth - 14, 23, { align: 'right' });

  doc.setTextColor(...MUTED_RGB);
  doc.setFontSize(9);
  doc.text(`Generated by ${document.metadata.generatedBy}`, 14, 34);
  doc.text(`Environment: ${document.metadata.environment}`, 14, 39);

  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Executive Summary', 14, 48);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const summary = document.executiveSummary ?? 'Official WILMS export document.';
  const wrapped = doc.splitTextToSize(summary, pageWidth - 28);
  doc.text(wrapped, 14, 54);

  return 54 + wrapped.length * 4 + 6;
}

function renderSummarySection(
  doc: jsPDF,
  section: WilmsExportSection,
  startY: number,
): number {
  autoTable(doc, {
    startY,
    head: [[section.title, '']],
    body: (section.summaryItems ?? []).map((item) => [item.label, item.value]),
    theme: 'grid',
    headStyles: {
      fillColor: PRIMARY_RGB,
      textColor: 255,
      fontStyle: 'bold',
    },
    alternateRowStyles: { fillColor: [245, 247, 246] },
    styles: { fontSize: 8, cellPadding: 2 },
    columnStyles: {
      0: { cellWidth: 55, fontStyle: 'bold' },
      1: { cellWidth: 'auto' },
    },
  });

  return (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? startY + 20;
}

function renderMetricsSection(doc: jsPDF, section: WilmsExportSection, startY: number): number {
  autoTable(doc, {
    startY,
    head: [[section.title, 'Value']],
    body: (section.metrics ?? []).map((metric) => [metric.label, metric.value]),
    theme: 'striped',
    headStyles: { fillColor: ACCENT_RGB, textColor: 255 },
    styles: { fontSize: 8, cellPadding: 2 },
  });

  return (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? startY + 20;
}

function renderTableSection(doc: jsPDF, section: WilmsExportSection, startY: number): number {
  const table = section.table!;

  autoTable(doc, {
    startY,
    head: [[section.title]],
    body: [],
    theme: 'plain',
    headStyles: {
      fillColor: PRIMARY_RGB,
      textColor: 255,
      fontSize: 10,
    },
  });

  const tableStart =
    ((doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? startY) + 2;

  autoTable(doc, {
    startY: tableStart,
    head: [table.headers],
    body: table.rows,
    foot: table.totalsRow ? [table.totalsRow] : undefined,
    theme: 'striped',
    headStyles: {
      fillColor: PRIMARY_RGB,
      textColor: 255,
      fontStyle: 'bold',
    },
    footStyles: {
      fillColor: [245, 247, 246],
      textColor: 0,
      fontStyle: 'bold',
    },
    alternateRowStyles: { fillColor: [245, 247, 246] },
    styles: { fontSize: 7, cellPadding: 2, overflow: 'linebreak' },
  });

  return (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? tableStart + 20;
}

function drawFooters(doc: jsPDF, document: WilmsExportDocument): void {
  const pageCount = doc.getNumberOfPages();

  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    doc.setDrawColor(...PRIMARY_RGB);
    doc.setLineWidth(0.4);
    doc.line(14, pageHeight - 16, pageWidth - 14, pageHeight - 16);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...MUTED_RGB);
    doc.text(WILMS_ORG_NAME, 14, pageHeight - 10);
    doc.text(`Page ${page} of ${pageCount}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    doc.text(document.metadata.reportId, pageWidth - 14, pageHeight - 10, { align: 'right' });
    doc.text(
      `${WILMS_CONFIDENTIALITY_NOTICE} Generated on ${document.metadata.generatedAt}`,
      14,
      pageHeight - 6,
      { maxWidth: pageWidth - 28 },
    );
  }
}

async function downloadRegistrationAgreementPdf(
  content: RegistrationAgreementContent,
  filename: string,
): Promise<void> {
  if (typeof window === 'undefined') {
    throw new Error('PDF export is only available in the browser.');
  }

  const html = buildRegistrationAgreementPrintHtml(content);
  const host = window.document.createElement('iframe');
  host.style.position = 'fixed';
  host.style.left = '-10000px';
  host.style.top = '0';
  host.style.width = '794px';
  host.style.height = '1123px';
  host.style.border = '0';
  host.title = 'Registration agreement PDF render';
  window.document.body.appendChild(host);

  const frameDocument = host.contentDocument ?? host.contentWindow?.document;

  if (!frameDocument) {
    host.remove();
    throw new Error('Unable to render registration PDF.');
  }

  frameDocument.open();
  frameDocument.write(html);
  frameDocument.close();

  await new Promise<void>((resolve) => {
    host.addEventListener('load', () => resolve(), { once: true });
    window.setTimeout(resolve, 500);
  });

  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });

  await new Promise<void>((resolve, reject) => {
    doc.html(frameDocument.body, {
      callback: (savedDoc) => {
        savedDoc.save(filename.endsWith('.pdf') ? filename : `${filename}.pdf`);
        host.remove();
        resolve();
      },
      x: 8,
      y: 8,
      width: 194,
      windowWidth: 794,
      autoPaging: 'text',
      html2canvas: { scale: 1, useCORS: true, logging: false },
    }).catch((error: unknown) => {
      host.remove();
      reject(error);
    });
  });
}

export async function downloadWilmsPdf(document: WilmsExportDocument, filename: string): Promise<void> {
  if (document.registrationAgreement) {
    await downloadRegistrationAgreementPdf(document.registrationAgreement, filename);
    return;
  }

  const orientation = document.orientation ?? 'portrait';
  const doc = new jsPDF({ orientation, unit: 'mm', format: 'a4' });

  let cursorY = drawDocumentHeader(doc, document);

  for (const section of document.sections) {
    if (cursorY > doc.internal.pageSize.getHeight() - 40) {
      doc.addPage();
      cursorY = 20;
    }

    switch (section.type) {
      case 'summary':
        cursorY = renderSummarySection(doc, section, cursorY) + 8;
        break;
      case 'metrics':
        cursorY = renderMetricsSection(doc, section, cursorY) + 8;
        break;
      case 'table':
        cursorY = renderTableSection(doc, section, cursorY) + 8;
        break;
      case 'text':
        doc.setFont('helvetica', 'bold');
        doc.text(section.title, 14, cursorY);
        doc.setFont('helvetica', 'normal');
        doc.text(doc.splitTextToSize(section.content ?? '', doc.internal.pageSize.getWidth() - 28), 14, cursorY + 6);
        cursorY += 20;
        break;
      default:
        break;
    }
  }

  if (document.signatures?.length) {
    if (cursorY > doc.internal.pageSize.getHeight() - 50) {
      doc.addPage();
      cursorY = 20;
    }

    autoTable(doc, {
      startY: cursorY,
      head: [['Authorized Signatures', 'Name', 'Date']],
      body: document.signatures.map((signature) => [signature.label, signature.name ?? '', '']),
      theme: 'grid',
      headStyles: { fillColor: PRIMARY_RGB, textColor: 255 },
      styles: { fontSize: 8, minCellHeight: 14 },
    });
  }

  drawFooters(doc, document);

  doc.save(filename.endsWith('.pdf') ? filename : `${filename}.pdf`);
}

export { WILMS_EXPORT_COLORS };
