export const AUDIT_ACTION = {
  BORROWER_REGISTERED: 'BORROWER_REGISTERED',
  BORROWER_APPROVED: 'BORROWER_APPROVED',
  BORROWER_REJECTED: 'BORROWER_REJECTED',
  BORROWER_BLACKLISTED: 'BORROWER_BLACKLISTED',
  PAYMENT_RECORDED: 'PAYMENT_RECORDED',
  PAYMENT_EDITED: 'PAYMENT_EDITED',
  OVERPAYMENT_FLAGGED: 'OVERPAYMENT_FLAGGED',
  OVERPAYMENT_REVIEWED: 'OVERPAYMENT_REVIEWED',
  ADJUSTMENT_REQUESTED: 'ADJUSTMENT_REQUESTED',
  ADJUSTMENT_APPROVED: 'ADJUSTMENT_APPROVED',
  ADJUSTMENT_REJECTED: 'ADJUSTMENT_REJECTED',
  RECONCILIATION_SUBMITTED: 'RECONCILIATION_SUBMITTED',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',
  GROUP_FLAGGED: 'GROUP_FLAGGED',
  GROUP_COLLECTOR_REASSIGNED: 'GROUP_COLLECTOR_REASSIGNED',
  GROUP_MEMBER_ADDED: 'GROUP_MEMBER_ADDED',
  GROUP_MEMBER_REMOVED: 'GROUP_MEMBER_REMOVED',
  GROUP_LEADER_REPLACED: 'GROUP_LEADER_REPLACED',
  GROUP_ADJUSTMENT_RECORDED: 'GROUP_ADJUSTMENT_RECORDED',
  GROUP_DISPLAY_NAME_UPDATED: 'GROUP_DISPLAY_NAME_UPDATED',
  RISK_FLAG_ESCALATED: 'RISK_FLAG_ESCALATED',
  RISK_FLAG_RESOLVED: 'RISK_FLAG_RESOLVED',
  RISK_FLAG_ASSIGNED: 'RISK_FLAG_ASSIGNED',
  RISK_FLAG_RAISED: 'RISK_FLAG_RAISED',
  SETTINGS_EXPORTED: 'SETTINGS_EXPORTED',
} as const;

export type AuditAction = (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];

export const AUDIT_TARGET_ENTITY = {
  BORROWER: 'BORROWER',
  PAYMENT: 'PAYMENT',
  RECONCILIATION: 'RECONCILIATION',
  ADJUSTMENT: 'ADJUSTMENT',
  OVERPAYMENT_REVIEW: 'OVERPAYMENT_REVIEW',
  USER: 'USER',
  GROUP: 'GROUP',
  RISK_FLAG: 'RISK_FLAG',
  SETTINGS: 'SETTINGS',
} as const;

export type AuditTargetEntity = (typeof AUDIT_TARGET_ENTITY)[keyof typeof AUDIT_TARGET_ENTITY];
