export const EMPTY_STATE_COPY = {
  borrowers: {
    title: 'No borrowers yet',
    description: 'This page lists every registered borrower once onboarding begins.',
    whyEmpty: 'No registrations have been submitted and approved yet.',
    howToStart: 'Registration officers submit applications; approvers review them before borrowers appear here.',
    actionHref: '/officer/register',
    actionLabel: 'Register a borrower',
  },
  loans: {
    title: 'No loans yet',
    description: 'Originated loans will appear here once disbursement begins.',
    whyEmpty: 'No loans have been created or disbursed for approved borrowers.',
    howToStart: 'Record admin fees, then originate a loan from the New Loan workflow.',
    actionHref: '/loans/new',
    actionLabel: 'Create a loan',
  },
  loanPools: {
    title: 'No loan pools yet',
    description: 'Loan pools hold the capital used for disbursements.',
    whyEmpty: 'No funding pools have been configured for the organisation.',
    howToStart: 'Create an operating pool before originating loans.',
    actionHref: '/loan-pools',
    actionLabel: 'View loan pools',
  },
  groups: {
    title: 'No groups yet',
    description: 'Lending groups organise borrowers for joint collection routes.',
    whyEmpty: 'Approved borrowers have not been grouped yet.',
    howToStart: 'Form a group once enough approved borrowers are ready.',
    actionHref: '/groups',
    actionLabel: 'Manage groups',
  },
  collectors: {
    title: 'No collectors yet',
    description: 'Collectors receive field assignments and post weekly collections.',
    whyEmpty: 'No collector profiles have been onboarded.',
    howToStart: 'Add collectors and assign groups from the collectors module.',
    actionHref: '/collectors',
    actionLabel: 'Manage collectors',
  },
  applications: {
    title: 'No pending applications',
    description: 'New borrower submissions awaiting your decision appear here.',
    whyEmpty: 'There are no pending applications in the approval queue right now.',
    howToStart: 'Registration officers submit applications that route here for review.',
  },
  reviewedApplications: {
    title: 'No reviewed applications yet',
    description: 'Your approval and rejection decisions are recorded here.',
    whyEmpty: 'You have not reviewed any applications yet.',
    howToStart: 'Open the pending queue to approve or reject the next application.',
    actionHref: '/approver/pending',
    actionLabel: 'Review pending applications',
  },
  payments: {
    title: 'No payments recorded',
    description: 'Repayments appear here after field collection is posted.',
    whyEmpty: 'No repayments have been recorded for the selected view.',
    howToStart: 'Collectors record payments from their assigned borrower routes.',
  },
  reports: {
    title: 'No report data yet',
    description: 'Reports populate once operational and financial activity exists.',
    whyEmpty: 'There is not enough activity yet to generate this report.',
    howToStart: 'Continue registrations, disbursements, and collections to build report data.',
  },
  notifications: {
    title: 'No notifications',
    description: 'Alerts and inbox messages appear here when generated.',
    whyEmpty: 'No system notifications have been delivered yet.',
    howToStart: 'Approvals, collections, and sync events will appear here automatically.',
  },
  riskFlags: {
    title: 'No risk flags',
    description: 'Raised risk signals appear here for triage and resolution.',
    whyEmpty: 'No operational risk signals have been raised.',
    howToStart: 'Missed payments, duplicates, and escalations will surface here when detected.',
  },
  adjustments: {
    title: 'No adjustments pending',
    description: 'Ledger adjustments requiring review appear here.',
    whyEmpty: 'There are no pending adjustment requests.',
    howToStart: 'Supervisors submit adjustments when corrections are needed after collection day.',
  },
  registrations: {
    title: 'No registrations yet',
    description: 'Your submitted borrower registrations appear here.',
    whyEmpty: 'You have not submitted any registrations yet.',
    howToStart: 'Start a new registration to capture borrower KYC and documents.',
    actionHref: '/officer/register',
    actionLabel: 'Start registration',
  },
  reconciliation: {
    title: 'No reconciliation data',
    description: 'Select a collection date to review or submit reconciliation totals.',
    whyEmpty: 'No reconciliation has been prepared for the selected period.',
    howToStart: 'Collectors submit end-of-day totals after field collections.',
    actionHref: '/collector/reconciliation',
    actionLabel: 'Open reconciliation',
  },
  dashboard: {
    title: 'No dashboard activity yet',
    description: 'KPIs and summaries appear once borrowers, loans, and collections exist.',
    whyEmpty: 'The programme has no operational activity to summarise yet.',
    howToStart: 'Register borrowers, originate loans, and record collections to populate KPIs.',
  },
  settings: {
    title: 'Settings unavailable',
    description: 'System settings could not be loaded right now.',
  },
  collectorsDashboard: {
    title: 'No collection assignments yet',
    description: 'Assigned groups and borrowers appear here once configured.',
    whyEmpty: 'You have no groups or borrowers assigned for collection yet.',
    howToStart: 'Contact an administrator to assign your collection route.',
  },
  adminFeeQueue: {
    title: 'No admin fees due',
    description: 'Borrowers awaiting administrative fee collection appear here.',
    whyEmpty: 'No approved borrowers are waiting for admin fee collection.',
    howToStart: 'Approved borrowers appear here before loan disbursement can proceed.',
  },
  overpayments: {
    title: 'No overpayment reviews',
    description: 'Overpayment cases requiring approval appear here.',
    whyEmpty: 'No overpayment reviews are pending.',
    howToStart: 'Overpayments detected during collection are routed here for supervisor review.',
  },
} as const;

export const CONNECTION_ERROR_COPY = {
  title: 'Unable to load this data',
  description: 'We could not reach the server. Check your connection and try again.',
} as const;
