import type { PermissionDefinition, RoleDefinition } from '@/types/user-management';
import { PERMISSION } from '@/constants/permissions';

export const PERMISSION_DEFINITIONS: PermissionDefinition[] = [
  { id: PERMISSION.ACCESS_ADMIN_PORTAL, label: 'Access admin portal', description: 'Enter the Super Admin console', category: 'Portal' },
  { id: PERMISSION.ACCESS_COLLECTOR_PORTAL, label: 'Access collector portal', description: 'Enter the field collector workspace', category: 'Portal' },
  { id: PERMISSION.ACCESS_REGISTRATION_PORTAL, label: 'Access registration portal', description: 'Enter the registration officer workspace', category: 'Portal' },
  { id: PERMISSION.ACCESS_APPROVER_PORTAL, label: 'Access approver portal', description: 'Enter the loan approver workspace', category: 'Portal' },
  { id: PERMISSION.ACCESS_AUDITOR_PORTAL, label: 'Access auditor portal', description: 'Enter the read-only auditor workspace', category: 'Portal' },
  { id: PERMISSION.REGISTER_BORROWERS, label: 'Register borrowers', description: 'Create new borrower registrations', category: 'Registration' },
  { id: PERMISSION.EDIT_BORROWERS, label: 'Edit borrowers', description: 'Update borrower profiles', category: 'Registration' },
  { id: PERMISSION.EDIT_PENDING_REGISTRATIONS, label: 'Edit pending registrations', description: 'Modify registrations awaiting approval', category: 'Registration' },
  { id: PERMISSION.CAPTURE_DOCUMENTS, label: 'Capture documents', description: 'Upload registration documents', category: 'Registration' },
  { id: PERMISSION.UPLOAD_SIGNATURES, label: 'Upload signatures', description: 'Capture borrower signatures', category: 'Registration' },
  { id: PERMISSION.GPS_VERIFICATION, label: 'GPS verification', description: 'Verify registration GPS coordinates', category: 'Registration' },
  { id: PERMISSION.MANAGE_GROUPS, label: 'Manage groups', description: 'Create and manage borrower groups', category: 'Collections' },
  { id: PERMISSION.VIEW_ASSIGNED_BORROWERS, label: 'View assigned borrowers', description: 'View borrowers assigned to the user', category: 'Collections' },
  { id: PERMISSION.RECORD_COLLECTIONS, label: 'Record collections', description: 'Record weekly repayments', category: 'Collections' },
  { id: PERMISSION.RECORD_EXPENSES, label: 'Record expenses', description: 'Submit field expenses', category: 'Finance' },
  { id: PERMISSION.VIEW_REPORTS, label: 'View reports', description: 'Access operational reports', category: 'Reports' },
  { id: PERMISSION.VIEW_FINANCIAL_REPORTS, label: 'View financial reports', description: 'Access financial and portfolio reports', category: 'Reports' },
  { id: PERMISSION.EXPORT_REPORTS, label: 'Export reports', description: 'Export PDF, CSV, and Excel reports', category: 'Reports' },
  { id: PERMISSION.REVIEW_APPLICATIONS, label: 'Review applications', description: 'Review pending application queue', category: 'Approval' },
  { id: PERMISSION.APPROVE_BORROWERS, label: 'Approve borrowers', description: 'Approve pending registrations', category: 'Approval' },
  { id: PERMISSION.APPROVE_LOANS, label: 'Approve loans', description: 'Approve loan disbursements', category: 'Approval' },
  { id: PERMISSION.REJECT_LOANS, label: 'Reject loans', description: 'Reject loan applications', category: 'Approval' },
  { id: PERMISSION.REVIEW_RISK_FLAGS, label: 'Review risk flags', description: 'Review and resolve risk flags', category: 'Audit' },
  { id: PERMISSION.VIEW_AUDIT_LOG, label: 'View audit logs', description: 'Read immutable audit records', category: 'Audit' },
  { id: PERMISSION.VIEW_AUDIT_HISTORY, label: 'View audit history', description: 'View user-level audit history', category: 'Audit' },
  { id: PERMISSION.VIEW_ALL_USERS, label: 'View all users', description: 'Browse the full user directory', category: 'Administration' },
  { id: PERMISSION.EDIT_USERS, label: 'Edit users', description: 'Update user profiles and assignments', category: 'Administration' },
  { id: PERMISSION.MANAGE_USERS, label: 'Manage users', description: 'Invite and manage staff accounts', category: 'Administration' },
  { id: PERMISSION.RESET_PASSWORD, label: 'Reset password', description: 'Force password reset for users', category: 'Administration' },
  { id: PERMISSION.RESET_PIN, label: 'Reset PIN', description: 'Reset device PIN for users', category: 'Administration' },
  { id: PERMISSION.SUSPEND_USERS, label: 'Suspend users', description: 'Suspend user accounts', category: 'Administration' },
  { id: PERMISSION.ACTIVATE_USERS, label: 'Activate users', description: 'Reactivate suspended accounts', category: 'Administration' },
  { id: PERMISSION.ASSIGN_PERMISSIONS, label: 'Assign permissions', description: 'Grant or revoke permission overrides', category: 'Administration' },
  { id: PERMISSION.ASSIGN_ROLES, label: 'Assign roles', description: 'Change user roles', category: 'Administration' },
  { id: PERMISSION.DELEGATE_AUTHORITY, label: 'Delegate authority', description: 'Delegate admin actions to other users', category: 'Administration' },
  { id: PERMISSION.FORCE_LOGOUT, label: 'Force logout', description: 'Terminate active user sessions', category: 'Administration' },
  { id: PERMISSION.ENABLE_MFA, label: 'Enable MFA', description: 'Configure multi-factor authentication', category: 'Administration' },
  { id: PERMISSION.MANAGE_ROLES, label: 'Manage roles', description: 'Create and edit role permissions', category: 'Administration' },
  { id: PERMISSION.MANAGE_SYSTEM_SETTINGS, label: 'Manage system settings', description: 'Configure platform settings', category: 'Administration' },
  { id: PERMISSION.MANAGE_EXPENSES, label: 'Manage expenses', description: 'Record and approve expenses', category: 'Finance' },
  { id: PERMISSION.VIEW_ALL_COLLECTORS, label: 'View all collectors', description: 'View organisation-wide collector roster', category: 'Administration' },
];

export const ROLE_DEFINITIONS: RoleDefinition[] = [
  {
    id: 'role-collector',
    name: 'Collector',
    description: 'Field collections and assigned borrower management',
    permissionIds: [
      PERMISSION.ACCESS_COLLECTOR_PORTAL,
      PERMISSION.REGISTER_BORROWERS,
      PERMISSION.MANAGE_GROUPS,
      PERMISSION.VIEW_ASSIGNED_BORROWERS,
      PERMISSION.RECORD_COLLECTIONS,
      PERMISSION.RECORD_EXPENSES,
    ],
    isSystem: true,
    userCount: 34,
  },
  {
    id: 'role-registration-officer',
    name: 'Registration Officer',
    description: 'Borrower onboarding and document capture',
    permissionIds: [
      PERMISSION.ACCESS_REGISTRATION_PORTAL,
      PERMISSION.REGISTER_BORROWERS,
      PERMISSION.EDIT_BORROWERS,
      PERMISSION.EDIT_PENDING_REGISTRATIONS,
      PERMISSION.CAPTURE_DOCUMENTS,
      PERMISSION.UPLOAD_SIGNATURES,
      PERMISSION.GPS_VERIFICATION,
    ],
    isSystem: true,
    userCount: 6,
  },
  {
    id: 'role-approver',
    name: 'Approver',
    description: 'Application and loan approval workflow',
    permissionIds: [
      PERMISSION.ACCESS_APPROVER_PORTAL,
      PERMISSION.REVIEW_APPLICATIONS,
      PERMISSION.APPROVE_LOANS,
      PERMISSION.REJECT_LOANS,
      PERMISSION.APPROVE_BORROWERS,
      PERMISSION.REVIEW_RISK_FLAGS,
    ],
    isSystem: true,
    userCount: 4,
  },
  {
    id: 'role-auditor',
    name: 'Auditor',
    description: 'Read-only compliance and audit access',
    permissionIds: [
      PERMISSION.ACCESS_AUDITOR_PORTAL,
      PERMISSION.VIEW_AUDIT_LOG,
      PERMISSION.VIEW_REPORTS,
      PERMISSION.EXPORT_REPORTS,
      PERMISSION.REVIEW_RISK_FLAGS,
    ],
    isSystem: true,
    userCount: 2,
  },
  {
    id: 'role-super-admin',
    name: 'Super Admin',
    description: 'Full platform administration',
    permissionIds: PERMISSION_DEFINITIONS.map((permission) => permission.id),
    isSystem: true,
    userCount: 2,
  },
];
