import type { BorrowerRegistrationFormValues } from '@/types/borrower-registration';
import type { RegisterBorrowerPayload } from '@/types/borrower-registration';
import type { BorrowerRegistrationInput } from '@/features/borrower-registration/registration.schema';
import type { BorrowerReviewDetail } from '@/types/approval';

export const DEFAULT_REGISTRATION_VALUES: BorrowerRegistrationFormValues = {
  fullName: '',
  dateOfBirth: '',
  gender: '',
  phone: '',
  email: '',
  nationality: 'Ghanaian',
  idType: '',
  idNumber: '',
  idDocument: null,
  idDocumentUploadId: undefined,
  houseAddress: '',
  gpsAddress: '',
  city: '',
  region: '',
  district: '',
  businessName: '',
  businessAddress: '',
  typeOfWork: '',
  typeOfWorkOther: '',
  guarantorName: '',
  guarantorPhone: '',
  guarantorRelationship: '',
  guarantorIdType: '',
  guarantorIdNumber: '',
  guarantorPhoto: null,
  photo: null,
  photoUploadId: undefined,
  guarantorPhotoUploadId: undefined,
  borrowerSignatureUploadId: undefined,
  borrowerThumbprintUploadId: undefined,
  guarantorSignatureUploadId: undefined,
  guarantorThumbprintUploadId: undefined,
  officerSignatureUploadId: undefined,
  borrowerThumbprintManualPlaceholder: false,
  guarantorThumbprintManualPlaceholder: false,
};

export function reviewDetailToFormValues(detail: BorrowerReviewDetail): BorrowerRegistrationFormValues {
  return {
    ...DEFAULT_REGISTRATION_VALUES,
    fullName: detail.fullName ?? '',
    dateOfBirth: detail.dateOfBirth ?? '',
    gender: detail.gender ?? '',
    phone: detail.phone ?? '',
    email: detail.email ?? '',
    nationality: detail.nationality ?? 'Ghanaian',
    idType: detail.idType ?? '',
    idNumber: detail.idNumber ?? '',
    houseAddress: detail.houseAddress ?? '',
    gpsAddress: detail.gpsAddress ?? '',
    city: detail.city ?? '',
    region: detail.region ?? '',
    district: detail.district ?? '',
    businessName: detail.businessName ?? '',
    businessAddress: detail.businessAddress ?? '',
    typeOfWork: detail.typeOfWork ?? '',
    guarantorName: detail.guarantorName ?? '',
    guarantorPhone: detail.guarantorPhone ?? '',
    guarantorRelationship: detail.guarantorRelationship ?? '',
    photoUploadId: undefined,
    guarantorPhotoUploadId: undefined,
    photo: detail.photoUrl ? new File([], detail.photoFileName || 'photo.jpg') : null,
    guarantorPhoto: detail.guarantorPhotoUrl ? new File([], 'guarantor-photo.jpg') : null,
  };
}

export function toRegisterBorrowerPayload(
  input: BorrowerRegistrationInput,
  registeredByOfficerId: string,
): RegisterBorrowerPayload {
  return {
    registeredByOfficerId,
    fullName: input.fullName,
    dateOfBirth: input.dateOfBirth,
    gender: input.gender,
    phone: input.phone,
    email: input.email || undefined,
    nationality: input.nationality,
    idType: input.idType,
    idNumber: input.idNumber,
    houseAddress: input.houseAddress,
    gpsAddress: input.gpsAddress,
    city: input.city,
    region: input.region,
    district: input.district,
    businessName: input.businessName,
    businessAddress: input.businessAddress,
    typeOfWork:
      input.typeOfWork === 'Other' && input.typeOfWorkOther?.trim()
        ? input.typeOfWorkOther.trim()
        : input.typeOfWork,
    guarantorName: input.guarantorName,
    guarantorPhone: input.guarantorPhone,
    guarantorRelationship: input.guarantorRelationship,
    photoFileName: input.photoUploadId ?? input.photo.name,
    photoMimeType: input.photo.type,
    photoUploadId: input.photoUploadId,
    guarantorPhotoUploadId: input.guarantorPhotoUploadId,
    idDocumentUploadId: input.idDocumentUploadId,
    borrowerSignatureUploadId: input.borrowerSignatureUploadId,
    borrowerThumbprintUploadId: input.borrowerThumbprintUploadId,
    guarantorSignatureUploadId: input.guarantorSignatureUploadId,
    guarantorThumbprintUploadId: input.guarantorThumbprintUploadId,
    officerSignatureUploadId: input.officerSignatureUploadId,
  };
}
