import type { BorrowerRegistrationFormValues } from '@/types/borrower-registration';
import type { RegisterBorrowerPayload } from '@/types/borrower-registration';
import type { BorrowerRegistrationInput } from '@/features/borrower-registration/registration.schema';

export const DEFAULT_REGISTRATION_VALUES: BorrowerRegistrationFormValues = {
  fullName: '',
  dateOfBirth: '',
  gender: '',
  phone: '',
  email: '',
  nationality: 'Ghanaian',
  idType: '',
  idNumber: '',
  idDocument: null,
  idDocumentUploadId: undefined,
  houseAddress: '',
  gpsAddress: '',
  city: '',
  region: '',
  district: '',
  businessName: '',
  businessAddress: '',
  typeOfWork: '',
  guarantorName: '',
  guarantorPhone: '',
  guarantorRelationship: '',
  guarantorIdType: '',
  guarantorIdNumber: '',
  guarantorPhoto: null,
  photo: null,
  photoUploadId: undefined,
  guarantorPhotoUploadId: undefined,
  borrowerSignatureUploadId: undefined,
  borrowerThumbprintUploadId: undefined,
  guarantorSignatureUploadId: undefined,
  guarantorThumbprintUploadId: undefined,
  officerSignatureUploadId: undefined,
  borrowerThumbprintManualPlaceholder: false,
  guarantorThumbprintManualPlaceholder: false,
};

export function toRegisterBorrowerPayload(
  input: BorrowerRegistrationInput,
  registeredByOfficerId: string,
): RegisterBorrowerPayload {
  return {
    registeredByOfficerId,
    fullName: input.fullName,
    dateOfBirth: input.dateOfBirth,
    gender: input.gender,
    phone: input.phone,
    email: input.email || undefined,
    nationality: input.nationality,
    idType: input.idType,
    idNumber: input.idNumber,
    houseAddress: input.houseAddress,
    gpsAddress: input.gpsAddress,
    city: input.city,
    region: input.region,
    district: input.district,
    businessName: input.businessName,
    businessAddress: input.businessAddress,
    typeOfWork: input.typeOfWork,
    guarantorName: input.guarantorName,
    guarantorPhone: input.guarantorPhone,
    guarantorRelationship: input.guarantorRelationship,
    photoFileName: input.photoUploadId ?? input.photo.name,
    photoMimeType: input.photo.type,
    photoUploadId: input.photoUploadId,
    guarantorPhotoUploadId: input.guarantorPhotoUploadId,
    idDocumentUploadId: input.idDocumentUploadId,
    borrowerSignatureUploadId: input.borrowerSignatureUploadId,
    borrowerThumbprintUploadId: input.borrowerThumbprintUploadId,
    guarantorSignatureUploadId: input.guarantorSignatureUploadId,
    guarantorThumbprintUploadId: input.guarantorThumbprintUploadId,
    officerSignatureUploadId: input.officerSignatureUploadId,
  };
}
