import { describe, expect, it, beforeEach, vi, afterEach } from 'vitest';
import { buildBorrowerProfileExportDocument } from '@/features/export/builders/borrower-profile-document';
import { buildTabularExportDocument } from '@/features/export/builders/tabular-export-document';
import { buildWilmsCsvContent } from '@/features/export/engines/csv-engine';
import {
  buildWilmsPrintHtml,
  printWilmsDocument,
  openWilmsPrintPreview,
} from '@/features/export/engines/print-engine';
import { WILMS_REPORT_TYPE } from '@/features/export/types';
import { generateReportId, resetReportIdSequence } from '@/features/export/utils/report-id';
import { BORROWER_STATUS, type BorrowerFullProfile } from '@/types/borrower';

describe('WILMS export framework', () => {
  beforeEach(() => {
    resetReportIdSequence();
  });

  it('generates traceable report IDs', () => {
    expect(generateReportId(WILMS_REPORT_TYPE.GROUP_LIST)).toBe('WILMS-GRP-2026-000001');
    expect(generateReportId(WILMS_REPORT_TYPE.AUDIT_LOG)).toBe('WILMS-AUD-2026-000002');
  });

  it('builds CSV with metadata preamble and human-readable headers', () => {
    const document = buildTabularExportDocument({
      reportType: WILMS_REPORT_TYPE.BORROWER_LIST,
      reportTitle: 'Borrower Directory Export',
      generatedBy: 'Super Admin',
      headers: ['Borrower ID', 'Full Name'],
      rows: [['borrower-001', 'Ama Mensah']],
      reportId: 'WILMS-BOR-2026-000123',
    });

    const csv = buildWilmsCsvContent(document);

    expect(csv).toContain('# Report ID: WILMS-BOR-2026-000123');
    expect(csv).toContain('# Generated By: Super Admin');
    expect(csv).toContain('Borrower ID,Full Name');
    expect(csv).toContain('borrower-001,Ama Mensah');
    expect(csv).toContain('Executive Summary');
  });

  it('builds dedicated print HTML without shell navigation', () => {
    const document = buildTabularExportDocument({
      reportType: WILMS_REPORT_TYPE.LOAN_POOL,
      reportTitle: 'Loan Pools Export',
      generatedBy: 'Super Admin',
      headers: ['Pool ID', 'Pool Name'],
      rows: [['PL-001', 'Accra Metro Pool']],
      reportId: 'WILMS-POL-2026-000045',
    });

    const html = buildWilmsPrintHtml(document);

    expect(html).toContain('WILMS');
    expect(html).toContain("Women's Interest-Free Loan Management System");
    expect(html).toContain('WILMS-POL-2026-000045');
    expect(html).toContain('Executive Summary');
    expect(html).toContain('Accra Metro Pool');
    expect(html).not.toContain('app-sidebar');
    expect(html).not.toContain('window.open');
  });

  it('builds borrower profile export with required sections', () => {
    const borrower: BorrowerFullProfile = {
      id: 'borrower-001',
      fullName: 'Ama Mensah',
      phone: '+233240000001',
      status: BORROWER_STATUS.APPROVED,
      groupName: 'Sunrise Women',
      groupId: 'GRP-0033',
      nationalId: 'GHA-123456789-0',
      community: 'Madina, Accra',
      registeredAt: '2025-01-15',
      gpsAddress: 'GA-123-4567',
      houseAddress: '12 Market Road',
      risk: {
        riskRating: 'Low Risk',
        missedPaymentCount: 0,
        defaultStatus: 'No',
        blacklistStatus: 'Clear',
        flags: [],
        notes: [],
      },
    };

    const document = buildBorrowerProfileExportDocument({
      borrower,
      generatedBy: 'Super Admin',
      loans: [],
      paymentLog: [],
      scheduleWeeks: [],
      variant: 'full',
    });

    expect(document.metadata.reportType).toBe(WILMS_REPORT_TYPE.BORROWER_PROFILE);
    expect(document.metadata.reportId).toMatch(/^WILMS-BOR-/);
    expect(document.sections.some((section) => section.title === 'Borrower Summary')).toBe(true);
    expect(document.sections.some((section) => section.title === 'Risk Summary')).toBe(true);
    expect(document.sections.some((section) => section.title === 'Audit Information')).toBe(true);
  });
});

describe('printWilmsDocument', () => {
  const sampleDocument = buildTabularExportDocument({
    reportType: WILMS_REPORT_TYPE.BORROWER_LIST,
    reportTitle: 'Print Test',
    generatedBy: 'Super Admin',
    headers: ['Borrower ID'],
    rows: [['BRW-0001']],
    reportId: 'WILMS-BOR-2026-000001',
  });

  afterEach(() => {
    vi.restoreAllMocks();
    document.getElementById('wilms-print-frame')?.remove();
    document.getElementById('wilms-print-preview-root')?.remove();
  });

  it('returns a result object and never throws', async () => {
    await expect(printWilmsDocument(sampleDocument)).resolves.toEqual(expect.objectContaining({ ok: expect.any(Boolean) }));
  });

  it('returns iframe_unavailable when iframe document is inaccessible', async () => {
    const originalCreateElement = document.createElement.bind(document);

    vi.spyOn(document, 'createElement').mockImplementation((tagName: string, options?: ElementCreationOptions) => {
      const element = originalCreateElement(tagName, options);

      if (tagName.toLowerCase() === 'iframe') {
        Object.defineProperty(element, 'contentDocument', { value: null });
        Object.defineProperty(element, 'contentWindow', { value: null });
      }

      return element;
    });

    const result = await printWilmsDocument(sampleDocument);

    expect(result).toEqual({ ok: false, reason: 'iframe_unavailable' });
  });

  it('returns print_blocked when print() throws', async () => {
    const originalCreateElement = document.createElement.bind(document);

    vi.spyOn(document, 'createElement').mockImplementation((tagName: string, options?: ElementCreationOptions) => {
      const element = originalCreateElement(tagName, options) as HTMLIFrameElement;

      if (tagName.toLowerCase() === 'iframe') {
        const frameDocument = document.implementation.createHTMLDocument('print');
        const mockWindow = {
          focus: vi.fn(),
          print: vi.fn(() => {
            throw new Error('Print blocked');
          }),
          document: frameDocument,
        };

        Object.defineProperty(element, 'contentWindow', { value: mockWindow });
        Object.defineProperty(element, 'contentDocument', { value: frameDocument });
      }

      return element;
    });

    const result = await printWilmsDocument(sampleDocument);

    expect(result).toEqual({ ok: false, reason: 'print_blocked' });
  });

  it('openWilmsPrintPreview returns a result object and never throws', () => {
    expect(() => openWilmsPrintPreview(sampleDocument)).not.toThrow();

    const result = openWilmsPrintPreview(sampleDocument);

    expect(result).toEqual(expect.objectContaining({ ok: expect.any(Boolean) }));
    document.getElementById('wilms-print-preview-root')?.remove();
  });
});
